//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MESTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 153=(
        ///154=)
        ///156=,
        ///157=-
        ///158=.
        ///166=?
        ///167=A
        ///168=B
        ///169=C
        ///16A=D
        ///16B=E
        ///16C=F
        ///16D=G
        ///16E=H
        ///16F=I
        ///170=J
        ///171=K
        ///172=L
        ///173=M
        ///174=N
        ///175=O
        ///176=P
        ///177=Q
        ///178=R
        ///179=S
        ///17A=T
        ///17B=U
        ///17C=V
        ///17D=W
        ///17E=X
        ///17F=Y
        ///180=Z
        ///181=[
        ///182=\
        ///183=]
        ///184=^
        ///185=_
        ///186=`
        ///187=a
        ///188=b
        ///189=c
        ///18A=d
        ///18B=e
        ///18C=f
        ///18D=g
        ///18E=h
        ///18F=i
        ///190=j
        ///191=k
        ///192=l
        ///193=m
        ///194=n
        ///195=o
        ///196=p
        ///197=q
        ///198=r
        ///199=s
        ///19A=t
        ///19B=u
        ///19C=v
        ///19D=w
        ///19E=x
        ///19F=y
        ///1A0=z
        ///1000= .
        /// </summary>
        internal static string CharTable {
            get {
                return ResourceManager.GetString("CharTable", resourceCulture);
            }
        }
    }
}
